#!/usr/bin/env bash
# PreToolUse hook: deny edits to src/<feature>/README.md.
# Those READMEs are regenerated by `devcontainers/action` in the release
# workflow (and locally by the regenerate-feature-readme.sh PostToolUse hook).
set -euo pipefail

input=$(cat)

tool_name=$(printf '%s' "$input" | jq -r '.tool_name // ""')
case "$tool_name" in
  Write|Edit|MultiEdit|NotebookEdit) ;;
  *) exit 0 ;;
esac

file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // ""')
[ -z "$file_path" ] && exit 0

if [[ "$file_path" =~ (^|/)src/[^/]+/README\.md$ ]]; then
  jq -n --arg path "$file_path" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: ("Refusing to edit \($path): Feature READMEs are auto-generated by `devcontainers/action` in the release workflow. Edit devcontainer-feature.json or NOTES.md instead — the PostToolUse hook will regenerate the README locally.")
    }
  }'
  exit 0
fi

exit 0
